# Generated by Django 4.2.8 on 2024-01-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-10-02'),
            preserve_default=False,
        ),
    ]
